update pipeline templates

diff --git a/.devops/templates/node-job-setup/template.yaml b/.devops/templates/node-job-setup/template.yaml
--- a/.devops/templates/node-job-setup/template.yaml
+++ b/.devops/templates/node-job-setup/template.yaml
@@ -33,26 +33,35 @@ steps:
 # This is needed because the pipeline may point to a different commit than expected
 # The common case is when the previous stage pushed another commit
 - ${{ if ne(parameters.gitReference, 'none') }}:
-  - script: |
+  - bash: |
       git fetch && git checkout ${{ parameters.gitReference }}
     displayName: 'Checkout reference'  
 
-- script: |
+- bash: |
     cd ${{ parameters.projectDir }}
+    echo "current folder: $(pwd)"
   displayName: 'Move to project folder'  
 
 # If a Node version is defined explicitly by parameter, such version is used
 # Else, version is red from .node-version file
 # Else, version is red from .nvmrc file
 - ${{ if ne(parameters.nodeVersion, 'none') }}:
-  - script: |
+  - bash: |
+      echo "current folder: $(pwd)"
       FROM_PARAM=${{ parameters.nodeVersion }}
+      echo "set FROM_PARAM='$FROM_PARAM'"
       echo "##vso[task.setvariable variable=NODE_VERSION]$FROM_PARAM"
+    workingDirectory: ${{ parameters.projectDir }}
     displayName: 'Determine Node.js version from template param'
 - ${{ if eq(parameters.nodeVersion, 'none') }}:
-  - script: |
+  - bash: |
+      echo "current folder: $(pwd)"
       FROM_SOURCE=$(cat .node-version || cat .nvmrc)
+      ls .node-version && echo ".node-version found, value: '$(cat .node-version)'" || echo ".node-version not found" 
+      ls .nvmrc && echo ".nvmrc found, value: '$(cat .nvmrc)'" || echo ".nvmrc not found" 
+      echo "set FROM_SOURCE='$FROM_SOURCE'"
       echo "##vso[task.setvariable variable=NODE_VERSION]$FROM_SOURCE"
+    workingDirectory: ${{ parameters.projectDir }} 
     displayName: 'Determine Node.js version from source'
 
 - task: UseNode@1
@@ -60,7 +69,7 @@ steps:
     version: $(NODE_VERSION)
   displayName: 'Set up Node.js'
 
-- script: |	
+- bash: |	
     echo registry=https://registry.npmjs.com/ >> .npmrc	
     echo \//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN >> .npmrc	
     echo \@pagopa:registry=https://npm.pkg.github.com/ >> .npmrc	
@@ -68,6 +77,9 @@ steps:
     GITHUB_TOKEN: $(GITHUB_TOKEN)    	
   displayName: 'Npm config'
 
-- script: |
+- bash: |
+    echo "current folder: $(pwd)"
     yarn install --frozen-lockfile --no-progress --non-interactive --network-concurrency 1 
+  workingDirectory: ${{ parameters.projectDir }}    
   displayName: 'Install node modules'
+
